---
name: Sofrware CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'software/**'
      - '.github/workflows/software.yml'
  pull_request:
    paths:
      - 'software/**'
      - '.github/workflows/software.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  staticcheck:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      # Get the repositery's code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.x'
          check-latest: true
          cache: true

      - run: "cd software; go test ./..."
      - run: "cd software; go vet ./..."
      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "2024.1.1"
          install-go: false
          working-directory: ./software
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu
        go:
          - 21
          - 22
          - 23
    name: 'tests on ${{ matrix.platform }} | 1.${{ matrix.go }}.x'
    runs-on: ${{ matrix.platform }}-latest
    steps:
      # Get the repositery's code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.${{ matrix.go }}.x'
          cache: true

      - name: Run tests
        run: "cd software; go clean -testcache && go test -race -cover -covermode=atomic ./..."
